### ISSUE TITLE
Multi Process Error

### ISSUE THREAD

**Issue by go-with-me000** [pytorch/torcheval#92] opened 2022-11-24 06:07 UTC
### 🐛 Describe the bug

When I run "distributed_example. py", I find that if the number of processes exceeds 3, an error will occur. I find that "gathered_metric_list" will always remain None. I have 7 GPUs. The same error occurs in the "test_toolkit. py" under the test folder. So what might be the cause of this problem?

### Versions

PyTorch version: 1.12.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.8.0 (default, Nov  6 2019, 21:49:08)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-4.4.0-142-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 10.1.243
CUDA_MODULE_LOADING set to:
GPU models and configuration:
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX TITAN X
GPU 3: GeForce GTX TITAN X
GPU 4: GeForce GTX TITAN X
GPU 5: GeForce GTX TITAN X
GPU 6: GeForce GTX TITAN X

Nvidia driver version: 460.56
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.4
[pip3] torch==1.12.0
[pip3] torcheval==0.0.5
[pip3] torcheval-nightly==2022.11.19
[pip3] torchmetrics==0.10.3
[pip3] torchtnt==0.0.3
[conda] blas                      1.0                         mkl    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl                       2020.2                      256    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] numpy                     1.23.4                    <pip>
[conda] pytorch                   1.13.0              py3.8_cpu_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
[conda] pytorch-mutex             1.0                         cpu    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
[conda] torch                     1.12.0                    <pip>
[conda] torcheval                 0.0.5                     <pip>
[conda] torcheval-nightly         2022.11.19                <pip>
[conda] torchmetrics              0.10.3                    <pip>
[conda] torchtnt                  0.0.3                     <pip>

**Comment by bobakfb** [comment] 2022-11-28 18:34
Hi @go-with-me000 I am not able to reproduce your issue on CPU, can you check if this happens on CPU as well? I will see if I can find an 8 GPU machine to test.

**Comment by bobakfb** [comment] 2022-11-29 01:31
Hi @go-with-me000 I was able to confirm I can run the example over 8 GPUs. Does this happen when you run with 3 GPUs? I'm wondering if this might be some issue with mixing and matching GPUs, but this is not my expertise.

**Comment by bobakfb** [comment] 2022-12-27 17:44
Closing since the user doesn't seem to have any updates.

**Closed by bobakfb** 2022-12-27 17:44 UTC
