### ISSUE TITLE
can not find package

### ISSUE THREAD

**Issue by go-with-me000** [pytorch/torcheval#89] opened 2022-11-21 04:23 UTC
### 🐛 Describe the bug

from torchtnt.utils.version import is_torch_version_geq_1_12
I found that this package does not exist. What is the version of torchtnt?
Or is something else wrong?

### Versions

from torchtnt.utils.version import is_torch_version_geq_1_12
I found that this package does not exist. What is the version of torchtnt?
Or is something else wrong?

**Comment by bobakfb** [comment] 2022-11-21 20:32
Hi @go-with-me000 is this an issue with the install? How do you reproduce this error?

**Comment by go-with-me000** [comment] 2022-11-22 02:23
Sorry, this problem is the version of the installation package I have. I have found the correct way to run it, but I have encountered a new problem. When I run "distributed_example. py", I find that if the number of processes exceeds 3, an error will occur. I find that "gathered_metric_list" will always remain None. I have 7 GPUs. The same error occurs in the "test_toolkit. py" under the test folder. So what might be the cause of this problem?

**Comment by bobakfb** [comment] 2022-11-22 02:33
@go-with-me000 Okay, I'm closing this issue. If you want to add a note on what exactly you changed that might help other users who run into the same error, I was not able to reproduce on my end. 

As for the new error, I'm happy to help you debug, but could you please post a new issue with full errors pasted in? This way if a new user runs into the problem it will be easier for them to find.

**Closed by bobakfb** 2022-11-22 02:33 UTC
